name: kubeflow-interactive-tutorial
version: '1.0'
summary: Kubeflow Interactive Tutorial POC
description: |
  This is a POC of the Kubeflow Interactive Tutorial application.
confinement: strict

base: core22

parts:
  frontend:
    plugin: npm
    source: ./frontend
    npm-include-node: true
    npm-node-version: "18.16.1"

  backend:
    plugin: npm
    source: ./backend
    npm-include-node: true
    npm-node-version: "18.16.1"

apps:
  frontend:
    command: npm start --prefix $SNAP/frontend
    daemon: simple
    plugs: [network-bind]
    environment:
      PORT: "3000"
      NODE_ENV: "production"
  backend:
    command: npm start --prefix $SNAP/backend
    daemon: simple
    plugs: [network-bind]
    environment:
      PORT: "4000"
      NODE_ENV: "production"