name: kubeflow-interactive-tutorial
version: '1.0'
summary: Kubeflow Interactive Tutorial POC
description: |
  This is a POC of the Kubeflow Interactive Tutorial application.
confinement: strict

base: core22

apps:
  frontend:
    command: node frontend/server.js
    daemon: simple
    plugs: [network-bind]
    environment:
      PORT: "3000"
      NODE_ENV: "production"
  backend:
    command: node backend/server.js
    daemon: simple
    plugs: [network-bind]
    environment:
      PORT: "4000"
      NODE_ENV: "production"

parts:
  frontend:
    plugin: nodejs
    source: frontend
    node-engine: "18.16.1"

  backend:
    plugin: nodejs
    source: backend
    node-engine: "18.16.1"

